import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
const digest=s=>createHash('sha256').update(s).digest('hex');
export function installAdmin(app,db,createBooking){
 db.exec(`CREATE TABLE IF NOT EXISTS admin(id INTEGER PRIMARY KEY CHECK(id=1),username TEXT NOT NULL,salt TEXT NOT NULL,hash TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires INTEGER NOT NULL);`);
 const local=req=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress)&&['localhost','127.0.0.1','[::1]'].includes(req.hostname)&&!req.headers['x-forwarded-for'];
 const sameOrigin=(req,res,next)=>{if(req.headers.origin!==`${req.protocol}://${req.get('host')}`)return res.status(403).json({error:'Origin tidak diizinkan.'});next();};
 const attempts=new Map();const limit=(req,res,next)=>{const key=req.socket.remoteAddress;const now=Date.now();const state=attempts.get(key)||{n:0,until:now+900000};if(state.until<now){state.n=0;state.until=now+900000;}attempts.set(key,state);if(++state.n>20)return res.status(429).json({error:'Terlalu banyak percobaan. Tunggu 15 menit.'});next();};
 app.get('/api/setup',(req,res)=>{res.set('Cache-Control','no-store');res.json({needed:!db.prepare('SELECT id FROM admin').get(),local:local(req)});});
 app.post('/api/setup',sameOrigin,limit,(req,res)=>{if(!local(req))return res.status(403).json({error:'Setup hanya melalui localhost tanpa proxy.'});if(db.prepare('SELECT id FROM admin').get())return res.status(409).json({error:'Admin sudah dibuat.'});const {username,password}=req.body||{};if(typeof username!=='string'||! /^[a-zA-Z0-9_.-]{3,50}$/.test(username)||typeof password!=='string'||password.length<12||password.length>200)return res.status(400).json({error:'Username 3–50 karakter; password minimal 12 karakter.'});const salt=randomBytes(16).toString('hex');db.prepare('INSERT INTO admin VALUES(1,?,?,?)').run(username,salt,scryptSync(password,salt,64).toString('hex'));res.status(201).json({ok:true});});
 app.post('/api/login',sameOrigin,limit,(req,res)=>{const {username,password}=req.body||{};if(typeof password!=='string'||password.length>200)return res.status(401).json({error:'Username atau password salah.'});const admin=db.prepare('SELECT * FROM admin').get();const actual=scryptSync(password,admin?.salt||'dummy-salt',64);if(!admin||admin.username!==username||!timingSafeEqual(actual,Buffer.from(admin.hash,'hex')))return res.status(401).json({error:'Username atau password salah.'});const token=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires < ?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),csrf,Date.now()+8*3600000);res.cookie('session',token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='1',maxAge:8*3600000,path:'/'});res.json({csrf,username});});
 const auth=(req,res,next)=>{res.set('Cache-Control','no-store');const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8)||'';req.session=db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(digest(token),Date.now());if(!req.session)return res.status(401).json({error:'Silakan masuk.'});next();};
 const csrf=(req,res,next)=>{if(req.get('X-CSRF-Token')!==req.session.csrf)return res.status(403).json({error:'Token keamanan tidak valid.'});next();};
 app.post('/api/admin/bookings',auth,sameOrigin,csrf,createBooking);
 app.get('/api/me',auth,(req,res)=>res.json({csrf:req.session.csrf,username:db.prepare('SELECT username FROM admin').get().username}));
 app.post('/api/logout',auth,sameOrigin,csrf,(req,res)=>{db.prepare('DELETE FROM sessions WHERE token=?').run(req.session.token);res.clearCookie('session',{path:'/'});res.json({ok:true});});
 app.get('/api/bookings',auth,(req,res)=>res.json(db.prepare('SELECT * FROM bookings ORDER BY created DESC').all().map(b=>({...b,...JSON.parse(b.data),data:undefined}))));
 app.patch('/api/bookings/:id',auth,sameOrigin,csrf,(req,res)=>{const {status,dp,notes}=req.body||{};if(!['baru','dihubungi','menunggu_dp','dp_diterima','dikonfirmasi','selesai','batal'].includes(status)||!Number.isSafeInteger(dp)||dp<0||dp>100000000000||typeof notes!=='string'||notes.length>5000)return res.status(400).json({error:'Status, DP atau catatan tidak valid.'});const result=db.prepare('UPDATE bookings SET status=?,dp=?,notes=? WHERE id=?').run(status,dp,notes,req.params.id);if(!result.changes)return res.status(404).json({error:'Booking tidak ditemukan.'});res.json({ok:true});});
}
